version: '2'
services:
  printer_1:
    build:
        context: .
        args:
            version: 1.3.9
    stdin_open: true
    tty: true
    ports:
    - "5000:5000"
    volumes:
    - ${PWD}:/app
