version: '2'
services:
  printer_1_stg:
    build:
        context: .
        args:
            version: 1.3.9
    stdin_open: true
    tty: true
    ports:
    - "5101:5000"
    volumes:
    - ${PWD}:/app
    command: >
      sh -c "cp /app/opconfigs/config.yaml.1.stg /data/config.yaml
      && octoprint --iknowwhatimdoing --basedir /data --debug"
  printer_2_stg:
    build:
        context: .
        args:
            version: 1.3.9
    stdin_open: true
    tty: true
    ports:
    - "5102:5000"
    volumes:
    - ${PWD}:/app
    command: >
      sh -c "cp /app/opconfigs/config.yaml.2.stg /data/config.yaml
      && octoprint --iknowwhatimdoing --basedir /data --debug"
